### PR TITLE
Update task4_audio_tagging.yaml

### PR DESCRIPTION
**Pull request by akshitac8**

### CODE REVIEW

**Comment by pafoster** [comment]
Hi akshitac8, I was wondering what is the reason for this pull request?

**Comment by akshitac8** [comment]
Hello,
I was working with the dcase code and was having issue with the features
and then I got your code which gave me good results but some modifications
were needed. So I thought these modifications can help the future ones who
will use your code.
Sorry if it caused you any inconvenience.

Thank you,
Regards
Akshita Gupta

**Comment by pafoster** [comment]
Hi Akshita,

Thank you for your response.

Please could you clarify which part of yor PR relates to error messages 
when running the code, and which part relates to classification 
performance improvements? If running the code produced errors, what were 
error messages?

Thanks,

Peter

**Comment by akshitac8** [comment]
Hello Peter,
If you compare the commits, you would see the changes made. When the main file is executed and `hamming window` of 1024 is maintained, the configuration given for `win_length_sec` and `hop_length_sec` is giving an _error_ for incompatible window configuration when run on **Windows**.

Thanks,
Akshita

**Comment by pafoster** [comment]
Hi Akshita,

In the commit, I was wondering about "thresh: None"? Is that change 
related to the same error?

Please could you send the precise error message you are receiving, your 
version of Python?

Peter

**Comment by akshitac8** [comment]
Hello peter,
For "thresh: None", It related to the GMM model syntax
Acc. to sklearn:
```
sklearn.mixture.GMM(n_components=1, covariance_type='diag', random_state=None, thresh=None, tol=0.001, min_covar=0.001, n_iter=100, n_init=1, params='wmc', init_params='wmc')
```
This is the default syntax so it is not taking thresh= null as a parameter
python version = 2.7

Thank you,
Akshita Gupta

**Comment by pafoster** [comment]
Hi Akshita,

I understand there are two issues that your PR addresses:

1) An issue with sklearn
2) An issue with the window size

Please could you send me the two error messages you were receiving, 
including stack traces, and I will try to reproduce the error on my 
machine.

Thanks,

Peter

**Comment by akshitac8** [comment]
Hi peter,

Kindly see the attached messages.
It would be great if you could merge the PR.
[https://drive.google.com/file/d/1xGYNgTD_FaKQEIRKotO4pFp0sM6QGxSR/view?usp=sharing](url)
[https://drive.google.com/file/d/1G3CJXjhdK7P-JnF2dKKAyKKveoQ7-cfQ/view?usp=sharing](url)
Thank you,
Akshita Gupta

**Comment by pafoster** [comment]
Hi Akshita,

Thank you. Additional question -- what version of sklearn are you using?

Peter

**Comment by akshitac8** [comment]
Hi Peter,

I'm using 0.18 version of sklearn.

Thank you,
Akshita

**Comment by akshitac8** [comment]
Hey,
Any update with PR?

Thank you,
Akshita

**Comment by pafoster** [comment]
Hi Akshita,

Thank you again for your comments. I've had a closer look at this.

I believe that changing the frame size to 0.064s is fine from the perspective of both correctness and reproducibility, due to the way that librosa 0.4.3 honoured the parameters passed to stft() -- the window size was sufficiently determined by n_fft and window, with no need for win_length. However, I would prefer to keep the existing hop size, to help ensure reproducibility of the existing results.

As far as I can see, the issue surrounding mixture.GMM is due to API changes in sklearn introduced in v0.18. As sklearn says that the class will be removed in v0.20, for the time being I have clarified the version requirements in README.md: They are Python 2.7, sklearm 0.17, librosa 0.4.3.

Please let me know if you encounter any other issues with the code.

Peter

**Pull request closed without merging**
